### ISSUE TITLE
Regression: Accordion (from `@cds/angular`) lost `expanded` event declaration from version 5.5.2 to 5.5.3 (in d.ts file)

### ISSUE THREAD

**Issue by thojo** [vmware/clarity#6639]
## Describe the bug

After updating Clarity from 5.5.1 to 5.6.2 I cannot longer use the `expanded` event of `<cds-accordion-panel>` because the `expandedChange` property is missing from the _d.ts_ file of `CdsAccordionPanelDirective`.

The build fails:

```html
  <cds-accordion-panel [expanded]="someState" (expandedChange)="setSomeState($event.detail)">...</cds-accordion-panel>
```

> error TS2339: Property 'detail' does not exist on type 'Event'.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-dark-theme-v5-a3szgg?devtoolsheight=33&file=src/app/app.component.html
2.  Wait for `npm install` / `ng serve` to finish.
3.  See build errors in terminal.

## Expected behavior

No build errors when using `expandedChange`'s `$event` with `<cds-accordion-panel>` like with versions up to 5.5.2.

Steps to see working state with version 5.5.2 in StackBlitz demo:

4.  Stop `ng serve` with ctrl+c.
5.  Change version of `@angular/cds` to 5.5.2 in _package.json_.
6.  Run `npm install` in terminal.
7.  Wait for `npm install` / `ng serve` to finish.
8.  Preview is usable and accordion works.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11 and 12

**Comment by coryrylan** [comment]
You can workaround this by using the `$any()` directive in the template
https://stackblitz.com/edit/clarity-dark-theme-v5-sv8hjs

```
(expandedChange)="collapsed = !$any($event).detail"
```

**Comment by thojo** [comment]
Yeah, thanks @coryrylan. I just realized that, too.

But my IDE still complains with a warning and other tooling might do the same.

However, it no longer blocks an update.
