### ISSUE TITLE
@clr/angular -  Compilation problem due to TS2611

### ISSUE THREAD

**Issue by karol-tarasiuk** [vmware/clarity#5015]
## @clr/angular -  Compilation problem due to TS2611

After updating from Clarity 2.4.5 to 4.0.1 I get problem with building Angular application. I get

```
ERROR in node_modules/@clr/angular/accordion/stepper/stepper-panel.d.ts:18:9 - error TS2611: 'id' is defined as a property in class 'ClrAccordionPanel', but is overridden here in 'ClrStepperPanel' as an accessor.

18     get id(): string;
           ~~
```

## How to reproduce

1.  Update `@clr/angular`, `@clr/icons`, `@clr/ui` from `2.4.5` to `4.0.1`.
2.  Update `@webcomponents/custom-elements` from `1.0.0.` to `1.4.2`
3.  Run `ng build`
4.  See error

## Expected behavior

Everything goes smooth :)

## Versions

**App**

- Angular: 10.1.0
- Node: 12.18.3
- Clarity: 4.0.1

**Comment by alexhildebrand** [comment]
+1

**Comment by StephenAlbrecht** [comment]
For the time being, you can get the project to compile by adding `"skipLibCheck": true` to the `"compilerOptions"` in `tsconfig.json`.

**Comment by onemadgeek** [comment]
+1

**Comment by gnomeontherun** [comment]
What version of TypeScript are you running?

**Comment by LubosD** [comment]
> What version of TypeScript are you running?

4.0.2

**Comment by simbro** [comment]
Same issue here - typescript version 3.7.3

**Comment by Jinnie** [comment]
Clarity v4 is using Angular 10.0.2, which is using Typescript 3.9.x.
We have yet to update to Angular 10.1.x and TS 4.0.2.

**Comment by gnomeontherun** [comment]
The concern about updating to TS 4 is that it might cause a breaking change. The workaround exists for the moment, but that is not the ideal. We need to inspect the output and determine if we can fix this in a backwards compatible way.

Angular making this change in a minor release is a little frustrating, as most of our breaking changes are related to build tooling and compiler changes in Angular instead of the actual Clarity library.

**Comment by adumesny** [comment]
if you start a new project `ng new test` + `ng add @clr` you get ang ~10.1.1, typescript ~4.0.2 but clr 4.x doesn't complain that it wants < ts 4 which is something you could fix in the meantime...

**Comment by gnomeontherun** [comment]
I have PR up and it should be in the next release this week.

**Comment by ReissZachary** [comment]
I was getting the same Compilation problem due to TS2611 as well. I tried `"skipLibCheck": true` which fixed that error. However, I am now getting errors like the following: 

ERROR in ./node_modules/@clr/angular/esm2015/utils/animations/expandable-animation/expandable-animation.js 33:8-43
"export 'ɵɵcomponentHostSyntheticListener' (imported as 'i0') was not found in '@angular/core'

ERROR in ./node_modules/@clr/angular/esm2015/utils/animations/expandable-animation/expandable-animation.js 35:8-39
"export 'ɵɵupdateSyntheticHostBinding' (imported as 'i0') was not found in '@angular/core'

ERROR in ./node_modules/@clr/angular/esm2015/utils/drag-and-drop/draggable-ghost.js 96:8-39
"export 'ɵɵupdateSyntheticHostBinding' (imported as 'i0') was not found in '@angular/core'

Any ideas what is going on and how to fix it?
