### ISSUE TITLE
Access column list on datagrid

### ISSUE THREAD

**Issue by Er1cG1ft** [vmware/clarity#2204]
**Select one ...**  (check one with "x")
```
[ ] bug
[ ] feature request
[x] enhancement
```

### Description
I am using a datagrid with a customizable set of columns that can be saved in "views" (a list of columns with a 'hidden' field to determine which columns to hide).  After adding/removing columns from the default view, I want users to be given an option to save a new view.  The only way I could get this working was to make the columnService public on the datagrid class, and subscribe to the column change event to determine which columns to save as 'hidden'.  Could you add a public method to get the columns' hidden attribute when it is updated, so I don't have to edit your source code?
Thanks!

**Comment by Er1cG1ft** [comment]
Thanks so much! This works perfectly.

**Comment by Kevin2iBi** [comment]
How can i set my custom column id or field name without filter?

**Comment by gnomeontherun** [comment]
@Kevin2iBi I'm not sure what you mean about filter, it is used purely to filter the list of columns to show only visible ones. Please post additional questions about implementation on Stack Overflow, we use GitHub issues for bugs and features.

**Comment by ph55** [comment]
Here we go again. 
After upgrading from version 1 to 2, workaround doesn't work anymore.

```ts
Property 'hidden' does not exist on type 'ClrDatagridColumn<any>'
```

**Comment by rosullivan-2** [comment]
I'm also seeing this issue. Seeing it now I've upgraded to v2.3.0.

**Comment by rosullivan-2** [comment]
> Here we go again.
> After upgrading from version 1 to 2, workaround doesn't work anymore.
> 
> ```ts
> Property 'hidden' does not exist on type 'ClrDatagridColumn<any>'
> ```

I'm also seeing this issue. Seeing it now I've upgraded to v2.3.0.

**Comment by ph55** [comment]
@rosullivan-2 We have now `clrDgHiddenChange` instead.
You can do something like that:

You have 
```ts
<clr-dg-column>
      <ng-template
        [clrDgHideableColumn]="..."
        (clrDgHiddenChange)="columnHiddenChange()"
      >
        {{ .... }}
      </ng-template>
</clr-dg-column>
```
