### PR TITLE
fix(core): improved event types

### LINKED ISSUE #6639: Regression: Accordion (from `@cds/angular`) lost `expanded` event declaration from version 5.5.2 to 5.5.3 (in d.ts file)
## Describe the bug

After updating Clarity from 5.5.1 to 5.6.2 I cannot longer use the `expanded` event of `<cds-accordion-panel>` because the `expandedChange` property is missing from the _d.ts_ file of `CdsAccordionPanelDirective`.

The build fails:

```html
  <cds-accordion-panel [expanded]="someState" (expandedChange)="setSomeState($event.detail)">...</cds-accordion-panel>
```

> error TS2339: Property 'detail' does not exist on type 'Event'.

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-dark-theme-v5-a3szgg?devtoolsheight=33&file=src/app/app.component.html
2.  Wait for `npm install` / `ng serve` to finish.
3.  See build errors in terminal.

## Expected behavior

No build errors when using `expandedChange`'s `$event` with `<cds-accordion-panel>` like with versions up to 5.5.2.

Steps to see working state with version 5.5.2 in StackBlitz demo:

4.  Stop `ng serve` with ctrl+c.
5.  Change version of `@angular/cds` to 5.5.2 in _package.json_.
6.  Run `npm install` in terminal.
7.  Wait for `npm install` / `ng serve` to finish.
8.  Preview is usable and accordion works.

## Versions

**Clarity project:**

- [ ] Clarity Core
- [x] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11 and 12

### LINKED ISSUE #6642: Regression: Empty boolean attributes are broken in @cds/angular@5.6.1 (and up)
## Describe the bug

After updating Clarity from 5.5.1 to 5.6.2 empty boolean attributes are evaluated as falsy. This was once already fixed for 5.2.1 in #5932.

```html
<cds-tag readonly>readonly tag</cds-tag>
```

## How to reproduce

1.  Go to https://stackblitz.com/edit/clarity-dark-theme-v5-ljlano?file=package.json
2.  Click on "Readonly Tag" an see interaction behaviour like "Clickable Tag", which shouldn't be there.
3.  Downgrade `@cds/angular` to 5.6.0
4.  Click on "Readonly Tag". There is no interaction behaviour.

## Expected behavior

Empty boolean attributes are interpreted as truthy/present like in version 5.6.0.

## Versions

**Clarity project:**

- [x] Clarity Core
- [ ] Clarity Angular/UI

**Clarity version:**

- [ ] v3.x
- [ ] v4.x
- [x] v5.x

**Framework:**

- [x] Angular
- [ ] React
- [ ] Vue
- [ ] Other:

**Framework version:**
Angular 11 and 12

## Additional notes

A workaround is to use property binding syntax:

```html
<cds-tag [readonly]="true">readonly tag</cds-tag>
```

### PR DESCRIPTION
**Pull request by coryrylan**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
Some metadata was missing when generating the cds-angular directives. This included certain event types due to not being listed as public or the event was not available as a TS doc annotation. This also fixes the boolean attribute support cds-angular for the directives when an empty attribute is set on an element.

closes https://github.com/vmware/clarity/issues/6639 
closes https://github.com/vmware/clarity/issues/6642

## What is the new behavior?
- add additional event/output types to custom element metadata
- boolean attribute support 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: packages/core/src/accordion/accordion-panel.element.ts [hunk 1]
```diff
@@ -71,7 +71,7 @@ export class CdsAccordionPanel extends LitElement {
 
   @querySlot('cds-accordion-content') private content: HTMLElement;
 
-  @event() protected expandedChange: EventEmitter<boolean>;
+  @event() expandedChange: EventEmitter<boolean>;
```
Comment (mathisscott) [inline packages/core/src/accordion/accordion-panel.element.ts:74]: 👍

File: packages/core/src/alert/alert.element.ts [hunk 2]
```diff
@@ -133,7 +133,7 @@ export function getAlertContentLayout(
  * @cssprop --close-icon-color-hover
  */
 export class CdsAlert extends LitElement {
-  @event() private closeChange: EventEmitter<boolean>;
+  @event() closeChange: EventEmitter<boolean>;
```
Comment (mathisscott) [inline packages/core/src/alert/alert.element.ts:136]: ❤️

File: packages/core/src/internal-components/overlay/overlay.element.ts [hunk 3]
```diff
@@ -73,7 +73,7 @@ export class CdsInternalStaticOverlay extends CdsBaseFocusTrap {
 
   private overlayIdPrefix = '_overlay-';
 
-  @event() protected closeChange: EventEmitter<CloseChangeSources>;
+  @event() closeChange: EventEmitter<CloseChangeSources>;
```
Comment (mathisscott) [inline packages/core/src/internal-components/overlay/overlay.element.ts:76]: 😅

**Review by mathisscott — APPROVED** [review]

**Review by hippee-lee — APPROVED** [review]
