### PR TITLE
fix(accordion): updated panel property to match stepper panel for TS 4

### LINKED ISSUE #5015: @clr/angular -  Compilation problem due to TS2611
## @clr/angular -  Compilation problem due to TS2611

After updating from Clarity 2.4.5 to 4.0.1 I get problem with building Angular application. I get

```
ERROR in node_modules/@clr/angular/accordion/stepper/stepper-panel.d.ts:18:9 - error TS2611: 'id' is defined as a property in class 'ClrAccordionPanel', but is overridden here in 'ClrStepperPanel' as an accessor.

18     get id(): string;
           ~~
```

## How to reproduce

1.  Update `@clr/angular`, `@clr/icons`, `@clr/ui` from `2.4.5` to `4.0.1`.
2.  Update `@webcomponents/custom-elements` from `1.0.0.` to `1.4.2`
3.  Run `ng build`
4.  See error

## Expected behavior

Everything goes smooth :)

## Versions

**App**

- Angular: 10.1.0
- Node: 12.18.3
- Clarity: 4.0.1

### PR DESCRIPTION
**Pull request by gnomeontherun**
There was an inconsistency in how the `id` property of the accordion panel and stepper panels were implemented that Typescript 4 did not like. This resolves the inconsistency and should work fine on TS 3.9 or 4. Angular bumped support to TS 4 and this is an unexpected side effect.

fixes #5015

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by hippee-lee — APPROVED** [review]

**Review by bdryanovski — APPROVED** [review]

**Comment by bdryanovski** [comment]
Adding this as a comment just for historical reasons 

[TypeScript TS2611](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#breaking-changes)

**Comment by bdryanovski** [comment]
@gnomeontherun I think that we gonna need PR for `v4`  branch as well

**Review by Jinnie — APPROVED** [review]
