### ISSUE TITLE
Latest 1.1.5 clarity causes exception when focusing our dropdowns

### ISSUE THREAD

**Issue by rbirkgit** [vmware/clarity#3610]
## Describe the bug

We have extended the clr-dropdown in our component and with latest Clarity 1.1.5 we are getting exceptions when focusing the control. It was working with 1.1.4

## How to reproduce

Focus the control. Exception seen:

`
core.js:15724 ERROR TypeError: Cannot read property 'disabled' of undefined
    at SafeSubscriber._next (clr-angular.js:17470)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:194)
    at SafeSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:132)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next (Subscriber.js:76)
    at Subscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (map.js:41)
    at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at ReplaySubject.push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next (Subject.js:47)
    at ReplaySubject.push../node_modules/rxjs/_esm5/internal/ReplaySubject.js.ReplaySubject.nextInfiniteTimeWindow (ReplaySubject.js:39)
    at DropdownFocusHandler.push../node_modules/@clr/angular/fesm5/clr-angular.js.DropdownFocusHandler.addChildren (clr-angular.js:17833)
`

## Expected behavior

No exception and working :)

## Versions

**App**

* Angular: [e.g. 7]
* Clarity: [e.g. 1.1.5]

**Device:**

* Browser [chrome 75]

## Additional notes

It's possible we are not using the dropdown properly, or this is a regression. We just updated Clarity with no other changes.

**Comment by Jinnie** [comment]
Unable to reproduce it on the website or with the latest v1 sources, please create a Stackblitz.

**Comment by rbirkgit** [comment]
Unfortunately it may take some time to create a stackkblitz. It's a lot of code we would need to convert and prepare. But something changed with 1.1.5 that causing our dropdown to get exceptions when it gets focus and then we can no longer type in it. Only first character gets there.

**Comment by rbirkgit** [comment]
I should add we have an input field inside the dropdown. That where we focus and type. That part was probably not obvious. It's our implementation of a type and filter dropdown where the options are shown depending on what the user typed so far.

**Comment by rbirkgit** [comment]
We can actually add this very simple html and reproduce the issue in our app. Creating a stackblitz with it doesn't show it. Not sure what we do different that would cause it.

`
<clr-dropdown>
  <div clrDropdownTrigger >
    <span>xxx</span>
  </div>
  <clr-dropdown-menu *clrIfOpen>
  </clr-dropdown-menu>
</clr-dropdown>
`

**Comment by rbirkgit** [comment]
Got a stackblitz that reproduce. You need latest Angular 7.x. Default Angulat is 7.2.10, but with 7.2.12 (which we use) causes the issue:

https://stackblitz.com/edit/clarity-custom-theme-v1-0-chjhu4

**Comment by gnomeontherun** [comment]
@rbirkgit There is an issue with the demo because you have an empty dropdown, which a recent change was added for accessibility to move focus into the dropdown and support keyboard navigation. However, without any items in the dropdown menu, this is throwing an error. We can add a better check on our end, but is that the case with your application as well or is there potentially something else?

**Comment by rbirkgit** [comment]
That may explain why sometimes I saw the issue and sometimes not. We dynamically load items (from backend) depending on a filter (an input box the user types in). Like a combo-edit box.

I think adding a guard against empty list would go along way.

**Comment by rbirkgit** [comment]
Btw, our control already supported keyboard navigation (simple key up/down, home/end). Will need to check how that interacts/conflicts with the new version. We may need to remove our code.

**Comment by gnomeontherun** [comment]
I see, the combobox would be the better choice component when that is available for async loading of contents. Until then we should guard against this issue, but a workaround for now is to conditionally have a button in the list while you are loading like this. 

```<button clrDropdownItem ngIf="!menu.length">Loading</button>```

**Comment by jkjha** [comment]
Just checked it works with v1.1.0 as well but fails with v1.1.5. Wondering why this minor release upgrade introduces this breaking change. Our production App was using @cli/ui:^1.1.0 and so it installed v1.1.5 which caused lot of functionalities to behave abnormally under dropdown.

**Comment by jeeyun** [comment]
Hi @jkjha, `[disabled]` attribute not working in 1.1.5 is definitely a regression and is fixed in 1.2.0. However, we will be deprecating the `[disabled]` attribute in the near future. This is because there's accessibility requirement to make disabled items focusable in an aria menu (you can read more about it in our doc under the Accessibility heading here: https://clarity.design/documentation/dropdowns).

What this means for you if you are on v1.x:
Upgrading to latest 1.x (1.2.1 at the moment) should give you limited working support for `[disabled]` attribute. We have added programmatic focus over all menu items as part of our accessibility fixes. However, in our cross browser testing we've found that any element with disabled attribute is not programmatically focusable in some browsers. It will still appear disabled but focus gets lost if you are trying to use keyboard navigation in one of the problematic browsers. Our recommendation post 1.2.1 is to use a new input `[clrDisabled]` which will apply the disabled style and aria attribute. It's up to the application make sure clicking on it doesn't activate that item.

**Comment by gnomeontherun** [comment]
The core issue here was fixed in #3706 and is released.
